In [1]:
import pandas as pd
df1=pd.read_csv('Datasets/house-prices-advanced-regression-techniques/train.csv')
df1.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## Exploratory Data Analysis

In [3]:
df1.shape

(1460, 81)

In [6]:
df1.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [10]:
dty=df1.dtypes
print(dty.array)

<NumpyExtensionArray>
[  dtype('int64'),   dtype('int64'),       dtype('O'), dtype('float64'),
   dtype('int64'),       dtype('O'),       dtype('O'),       dtype('O'),
       dtype('O'),       dtype('O'),       dtype('O'),       dtype('O'),
       dtype('O'),       dtype('O'),       dtype('O'),       dtype('O'),
       dtype('O'),   dtype('int64'),   dtype('int64'),   dtype('int64'),
   dtype('int64'),       dtype('O'),       dtype('O'),       dtype('O'),
       dtype('O'),       dtype('O'), dtype('float64'),       dtype('O'),
       dtype('O'),       dtype('O'),       dtype('O'),       dtype('O'),
       dtype('O'),       dtype('O'),   dtype('int64'),       dtype('O'),
   dtype('int64'),   dtype('int64'),   dtype('int64'),       dtype('O'),
       dtype('O'),       dtype('O'),       dtype('O'),   dtype('int64'),
   dtype('int64'),   dtype('int64'),   dtype('int64'),   dtype('int64'),
   dtype('int64'),   dtype('int64'),   dtype('int64'),   dtype('int64'),
   dtype('int64'),       dtype('O'),   dtype('int64'),       dtype('O'),
   dtype('int64'),       dtype('O'),       dtype('O'), dtype('float64'),
       dtype('O'),   dtype('int64'),   dtype('int64'),       dtype('O'),
       dtype('O'),       dtype('O'),   dtype('int64'),   dtype('int64'),
   dtype('int64'),   dtype('int64'),   dtype('int64'),   dtype('int64'),
       dtype('O'),       dtype('O'),       dtype('O'),   dtype('int64'),
   dtype('int64'),   dtype('int64'),       dtype('O'),       dtype('O'),
   dtype('int64')]
Length: 81, dtype: object

In [47]:
def treat_na(df,col):
    if pd.api.types.is_numeric_dtype(df[col]):
        df[col]=df[col].fillna(df[col].mean())
    return df

In [16]:
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

In [48]:
for col in df1.columns:
    df2=treat_na(df1,col)

In [24]:
df2[[col for col in df2.columns if pd.api.types.is_integer_dtype(df2[col])]].isnull().sum()

Id               0
MSSubClass       0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [35]:
isnull=df2.isnull().sum()

In [38]:
isnull.where(isnull>1000).dropna()

Alley          1369.0
PoolQC         1453.0
Fence          1179.0
MiscFeature    1406.0
dtype: float64

In [39]:
df2.drop(columns=['Alley','PoolQC','Fence','MiscFeature'],inplace=True)

In [41]:
df2.shape

(1460, 77)

In [42]:
df2.dropna(thresh=20,inplace=True)

In [44]:
df2.shape

(1460, 77)

In [50]:
df2[]

np.int64(0)

In [52]:
isnull_obj=df2[[col for col in df2.columns if pd.api.types.is_object_dtype(df2[col])]].isnull().sum() #df2.select_dtypes(include=['object'].isnull().sum()

In [57]:
null_columns=isnull_obj.where(isnull_obj>0).dropna().index

In [61]:
df2[null_columns].head()

,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond
0,BrkFace,Gd,TA,No,GLQ,Unf,SBrkr,NaN,Attchd,RFn,TA,TA
1,NaN,Gd,TA,Gd,ALQ,Unf,SBrkr,TA,Attchd,RFn,TA,TA
2,BrkFace,Gd,TA,Mn,GLQ,Unf,SBrkr,TA,Attchd,RFn,TA,TA
3,NaN,TA,Gd,No,ALQ,Unf,SBrkr,Gd,Detchd,Unf,TA,TA
4,BrkFace,Gd,TA,Av,GLQ,Unf,SBrkr,TA,Attchd,RFn,TA,TA

In [73]:
def treat_na_obj(df,col):
    if pd.api.types.is_object_dtype(df[col]):
        mod_val=df[col].values_counts().index[0]
        df[col]=df[col].fillna(mod_val)
    return df

In [74]:
for col in df2.columns:
    df3=treat_na(df2,col)

In [75]:
df3.select_dtypes(include=['object']).isnull().sum()

MSZoning           0
Street             0
LotShape           0
LandContour        0
Utilities          0
LotConfig          0
LandSlope          0
Neighborhood       0
Condition1         0
Condition2         0
BldgType           0
HouseStyle         0
RoofStyle          0
RoofMatl           0
Exterior1st        0
Exterior2nd        0
MasVnrType       872
ExterQual          0
ExterCond          0
Foundation         0
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Heating            0
HeatingQC          0
CentralAir         0
Electrical         1
KitchenQual        0
Functional         0
FireplaceQu      690
GarageType        81
GarageFinish      81
GarageQual        81
GarageCond        81
PavedDrive         0
SaleType           0
SaleCondition      0
dtype: int64